//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FF6PRE {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FF6PRE.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id,Master Designation
        ///1,Attack
        ///2,Defend
        ///3,Unlisted (Escape)
        ///4,Row
        ///5,Skip
        ///6,Trance
        ///7,Revert
        ///8,Steal
        ///9,Mug
        ///10,Throw
        ///11,Runic
        ///12,Sketch
        ///13,Control
        ///14,Slot
        ///15,Gil Toss
        ///16,Leap
        ///17,Mimic
        ///18,Pray
        ///19,Shock
        ///20,Possess
        ///21,Jump
        ///22,Jump (Fall)
        ///24,Tools
        ///31,&lt;IC_WMGC&gt;Cure
        ///32,&lt;IC_WMGC&gt;Cura
        ///33,&lt;IC_WMGC&gt;Curaga
        ///34,&lt;IC_WMGC&gt;Raise
        ///35,&lt;IC_WMGC&gt;Arise
        ///36,&lt;IC_WMGC&gt;Poisona
        ///37,&lt;IC_WMGC&gt;Esuna
        ///38,&lt;IC_WMGC&gt;Regen
        ///39,&lt;IC_WMGC&gt;Reraise
        ///40,&lt;IC_BMGC&gt;Fire
        ///41,&lt;IC_BMGC&gt;Blizzard
        ///42,&lt;IC_BMGC&gt;Thunder
        ///43,&lt;IC_BMGC&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ability {
            get {
                return ResourceManager.GetString("ability", resourceCulture);
            }
        }
    }
}
